# Generated by Django 4.2.20 on 2025-03-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lily', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('holiday', 'Holiday'), ('exam', 'Exam'), ('deadline', 'Deadline'), ('lecture', 'Lecture'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
