# Generated by Django 4.2.20 on 2025-03-24 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lily', '0005_calendarevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['date'], 'verbose_name': 'Calendar Event', 'verbose_name_plural': 'Calendar Events'},
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='user_email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
