# Generated by Django 4.2.20 on 2025-03-24 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lily', '0006_alter_calendarevent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('holiday', 'Holiday'), ('exam', 'Exam'), ('lecture', 'Lecture'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
