from django.contrib import admin
from django.urls import include,path
from lily import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.register, name='register'),
    path('login_view/', views.login_view, name='login'),
    path('calander/', views.calendar, name='calendar'),
    path('tables/', views.tables, name='tables'),
    path('tables2/', views.tables2, name='tables2'),
    path('tables3/', views.tables3, name='tables3'),
    path('tables4/', views.tables4, name='tables4'),
    path('christmas/', views.christmas, name='christmas'),
    path('newyear/', views.newyear, name='newyear'),
    path('guru/', views.guru, name='guru'),
    path('bhogi/', views.bhogi, name='bhogi'),
    path('sankranti/', views.sankranti, name='sankranti'),
    path('kanuma/', views.kanuma, name='kanuma'),
    path('swami/', views.swami, name='swami'),
    path('bosee/', views.bosee, name='bosee'),
    path('republic/', views.republic, name='republic'),
    path('valentine/', views.valentine, name='valentine'),
    path('shivaji/', views.shivaji, name='shivaji'),
    path('shiva/', views.shiva, name='shiva'),
    path('holi/', views.holi, name='holi'),
    path('ugadi/', views.ugadi, name='ugadi'),
    path('ramzan/', views.ramzan, name='ramzan'),
    path('ram/', views.ram, name='ram'),
    path('mahavir/', views.mahavir, name='mahavir'),
    path('ambedkar/', views.ambedkar, name='ambedkar'),
    path('gfriday/', views.gfriday, name='gfriday'),
    path('easter/', views.easter, name='easter'),
    path('tagore/', views.tagore, name='tagore'),
    path('mother/', views.mother, name='mother'),
    path('buddha/', views.buddha, name='buddha'),
    path('bakrid/', views.bakrid, name='bakrid'),
    path('kabir/', views.kabir, name='kabir'),
    path('father/', views.father, name='father'),
    path('muharam/', views.muharam, name='muharam'),
    path('friend/', views.friend, name='friend'),
    path('raksha/', views.raksha,name='raksha'),
    path('independance/', views.independance,name='independance'),
    path('krishna/', views.krishna,name='krishna'),
    path('ganesh/', views.ganesh,name='ganesh'),
    path('onam/', views.onam,name='onam'),
    path('teacher/', views.teacher,name='teacher'),
    path('durga/', views.durga,name='durga'),
    path('vijaya/', views.vijaya,name='vijaya'),
    path('gandhi/', views.gandhi,name='gandhi'),
    path('diwali/', views.diwali,name='diwali'),
    path('children/', views.children,name='children'),
    path('lily/', include('lily.urls')),
    path('get_events/', views.get_events, name='get_events'),
    path('add_event/', views.add_event, name='add_event'),
    path('events/update/', views.update_event, name='update_event'),
     path('delete_event/<int:event_id>/', views.delete_event, name='delete_event'),
    path('update_event/<int:event_id>/', views.update_event, name='update_event'),
    path('event_details/<int:event_id>/', views.event_details, name='event_details'),
    path('categorized_events/', views.categorized_events, name='categorized_events'),
]

